### ISSUE TITLE
Git Branching

### ISSUE THREAD

**Issue by Giovani-Brady** [nberardi/stripe-dotnet#41]
@paulirwin 
@nberardi 

we should consider using a simple branching model to better handle a production/development versions of this package as well as hotfix (bugs) and feature branches to handle bugs in the production branch and new features to be added to the development branch.

here's a more detailed explanation of the branch break downs and their purposes.
http://nvie.com/posts/a-successful-git-branching-model/

as I am still not a collaborator on this project only yourselves would be able to implement this on the main repository

**Comment by paulirwin** [comment]
For small libraries like this one, I prefer a simpler model without a develop branch, and tagging master for releases rather than creating release branches. So master would represent current development work and if you want to reference a past release you go to the tag. Feature branches are a good idea for features within the repo, and of course requiring feature branches on forks for PRs. If an issue is found in a release branch, you branch from the release tag, fix the issue there, and release a hotfix from that branch before merging back in. I do like the "A Successful Git Branching Model" for in-house projects i.e. web apps, but for open-source small libraries like this one the extra yak shaving is unnecessary to achieve the intended goals - keep large feature dev separate, be able to hotfix releases, and have an easy way of referencing past releases vs current dev.

**Comment by Giovani-Brady** [comment]
I see your point and agree, for as long as the project stays small. (with a small amount of us working on it anyway) this proposed model is good

@paulirwin 
Should we post some of these guidelines on addressing bugs in releases and adding features in the readme document for future collaborative reference?

I don't want to lose any of these discussions when closing issues.
